import type {
  User,
  Location,
  Report,
  Corroboration,
  StatusEvent,
  Comment,
  VerificationSignal,
  Notification,
  InternalNote,
} from './types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Ama Mensah',
    email: 'ama.mensah@st.university.edu.gh',
    hall_or_dept: 'Pentagon Hall',
    role: 'student',
    tempPasskey: 'password123',
  },
  {
    id: 'u2',
    name: 'Kwabena Owusu',
    email: 'kwabena.owusu@st.university.edu.gh',
    hall_or_dept: 'Republic Hall',
    role: 'student',
    tempPasskey: 'password123',
  },
  {
    id: 'u3',
    name: 'Akosua Frimpong',
    email: 'akosua.frimpong@st.university.edu.gh',
    hall_or_dept: 'Independence Hall',
    role: 'student',
    tempPasskey: 'password123',
  },
  {
    id: 'u4',
    name: 'Yaw Boateng',
    email: 'yaw.boateng@st.university.edu.gh',
    hall_or_dept: 'Continental Hall',
    role: 'student',
    tempPasskey: 'password123',
  },
  {
    id: 'u5',
    name: 'Esi Ansah',
    email: 'esi.ansah@st.university.edu.gh',
    hall_or_dept: 'SRC Office',
    role: 'rep',
    tempPasskey: 'password123',
  },
  {
    id: 'u6',
    name: 'Daniel Tetteh',
    email: 'daniel.tetteh@st.university.edu.gh',
    hall_or_dept: 'Maintenance Unit',
    role: 'staff',
    requiresPasswordChange: true,
    tempPasskey: 'STAFF-5520',
    onboardedAt: '2026-09-06T10:00:00Z',
  },
  {
    id: 'u7',
    name: 'Grace Adjei',
    email: 'grace.adjei@st.university.edu.gh',
    hall_or_dept: 'Student Affairs',
    role: 'admin',
    tempPasskey: 'password123',
  },
];

export const mockLocations: Location[] = [
  { id: 'l1', name: 'Pentagon Hall, Room 204', building_type: 'residence' },
  { id: 'l2', name: 'Pentagon Hall, Common Bathroom', building_type: 'residence' },
  { id: 'l3', name: 'Republic Hall, Room 112', building_type: 'residence' },
  { id: 'l4', name: 'Republic Hall, Block A Stairwell', building_type: 'residence' },
  { id: 'l5', name: 'Independence Hall, Room 318', building_type: 'residence' },
  { id: 'l6', name: 'Independence Hall, Kitchen Area', building_type: 'residence' },
  { id: 'l7', name: 'Continental Hall, Room 405', building_type: 'residence' },
  { id: 'l8', name: 'Continental Hall, Lobby', building_type: 'residence' },
  { id: 'l9', name: 'Main Library, 2nd Floor Reading Room', building_type: 'library' },
  { id: 'l10', name: 'Main Library, Ground Floor Restroom', building_type: 'library' },
  { id: 'l11', name: 'Engineering Block, Lecture Hall 3', building_type: 'academic' },
  { id: 'l12', name: 'Science Block, Lab 204', building_type: 'academic' },
  { id: 'l13', name: 'Business School, Auditorium', building_type: 'academic' },
  { id: 'l14', name: 'Administration Building, Office 12', building_type: 'administrative' },
  { id: 'l15', name: 'Sports Complex, Changing Room', building_type: 'sports' },
  { id: 'l16', name: 'Central Cafeteria, Dining Area', building_type: 'dining' },
  { id: 'l17', name: 'Central Cafeteria, Kitchen', building_type: 'dining' },
];

export const mockReports: Report[] = [
  {
    id: 'r1',
    student_id: 'u1',
    student_name: 'Ama Mensah',
    location_id: 'l2',
    location_name: 'Pentagon Hall, Common Bathroom',
    category: 'plumbing',
    description:
      'One of the shower heads in the common bathroom has been leaking continuously for three days. The floor is constantly wet and slippery, making it unsafe especially at night. Water is pooling near the drain and not draining properly.',
    photo_url: 'https://images.pexels.com/photos/6899476/pexels-photo-6899476.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'open',
    verification_score: 7,
    created_at: '2026-09-01T08:30:00Z',
  },
  {
    id: 'r2',
    student_id: 'u2',
    student_name: 'Kwabena Owusu',
    location_id: 'l4',
    location_name: 'Republic Hall, Block A Stairwell',
    category: 'structural',
    description:
      'There is a large crack in the stairwell wall on the second floor landing. Pieces of plaster have fallen off and the crack appears to be widening. This could be a safety hazard if left unaddressed.',
    photo_url: 'https://images.pexels.com/photos/533889/pexels-photo-533889.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'in_progress',
    verification_score: 12,
    created_at: '2026-08-28T14:15:00Z',
  },
  {
    id: 'r3',
    student_id: 'u3',
    student_name: 'Akosua Frimpong',
    location_id: 'l10',
    location_name: 'Main Library, Ground Floor Restroom',
    category: 'sanitation',
    description:
      'The ground floor restroom in the main library has been without soap and tissue paper for over a week. The hand dryer is also not working. Students are unable to maintain basic hygiene after using the facilities.',
    photo_url: null,
    status: 'resolved',
    verification_score: 15,
    created_at: '2026-08-20T09:00:00Z',
  },
  {
    id: 'r4',
    student_id: 'u4',
    student_name: 'Yaw Boateng',
    location_id: 'l11',
    location_name: 'Engineering Block, Lecture Hall 3',
    category: 'electrical',
    description:
      'Several power outlets in Lecture Hall 3 of the Engineering Block are not working. This affects students who need to charge their laptops during lectures. At least 4 out of 12 outlets appear to be dead.',
    photo_url: 'https://images.pexels.com/photos/3973531/pexels-photo-3973531.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'open',
    verification_score: 5,
    created_at: '2026-09-03T11:45:00Z',
  },
  {
    id: 'r5',
    student_id: 'u1',
    student_name: 'Ama Mensah',
    location_id: 'l6',
    location_name: 'Independence Hall, Kitchen Area',
    category: 'electrical',
    description:
      'The main light in the shared kitchen area of Independence Hall keeps flickering on and off. It has been getting worse over the past week and now goes completely dark for several seconds at a time. This is a safety concern for students cooking in the evening.',
    photo_url: 'https://images.pexels.com/photos/3973531/pexels-photo-3973531.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'in_progress',
    verification_score: 9,
    created_at: '2026-08-30T17:20:00Z',
  },
  {
    id: 'r6',
    student_id: 'u2',
    student_name: 'Kwabena Owusu',
    location_id: 'l16',
    location_name: 'Central Cafeteria, Dining Area',
    category: 'sanitation',
    description:
      'Several tables in the Central Cafeteria dining area have not been cleaned properly. There are food remnants and sticky surfaces on at least 6 tables near the entrance. This has been ongoing for two days.',
    photo_url: null,
    status: 'open',
    verification_score: 3,
    created_at: '2026-09-05T12:00:00Z',
  },
  {
    id: 'r7',
    student_id: 'u3',
    student_name: 'Akosua Frimpong',
    location_id: 'l15',
    location_name: 'Sports Complex, Changing Room',
    category: 'plumbing',
    description:
      'Two of the four shower stalls in the Sports Complex changing room have no hot water. The water goes from cold to freezing within seconds. This has been reported verbally to the sports office but nothing has been done.',
    photo_url: 'https://images.pexels.com/photos/6899476/pexels-photo-6899476.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'open',
    verification_score: 6,
    created_at: '2026-09-04T06:30:00Z',
  },
  {
    id: 'r8',
    student_id: 'u4',
    student_name: 'Yaw Boateng',
    location_id: 'l9',
    location_name: 'Main Library, 2nd Floor Reading Room',
    category: 'structural',
    description:
      'A ceiling panel in the 2nd floor reading room of the Main Library is sagging and looks like it could fall. It is directly above the study tables near the window. Students have moved to other areas out of caution.',
    photo_url: 'https://images.pexels.com/photos/533889/pexels-photo-533889.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'in_progress',
    verification_score: 10,
    created_at: '2026-08-27T10:00:00Z',
  },
  {
    id: 'r9',
    student_id: 'u1',
    student_name: 'Ama Mensah',
    location_id: 'l1',
    location_name: 'Pentagon Hall, Room 204',
    category: 'other',
    description:
      'The door handle to Room 204 in Pentagon Hall is loose and comes off when pulled. The lock mechanism also sticks, making it difficult to secure the room. This has been an issue for the past week.',
    photo_url: null,
    status: 'resolved',
    verification_score: 8,
    created_at: '2026-08-18T15:30:00Z',
  },
  {
    id: 'r10',
    student_id: 'u3',
    student_name: 'Akosua Frimpong',
    location_id: 'l17',
    location_name: 'Central Cafeteria, Kitchen',
    category: 'plumbing',
    description:
      'The kitchen sink in the Central Cafeteria is blocked and water backs up when in use. There is also a noticeable odor coming from the drain. This affects food preparation and hygiene standards.',
    photo_url: 'https://images.pexels.com/photos/6899476/pexels-photo-6899476.jpeg?auto=compress&cs=tinysrgb&w=600',
    status: 'open',
    verification_score: 4,
    created_at: '2026-09-06T07:45:00Z',
  },
];

export const mockCorroborations: Corroboration[] = [
  { id: 'c1', report_id: 'r1', student_id: 'u2', student_name: 'Kwabena Owusu', created_at: '2026-09-01T10:00:00Z' },
  { id: 'c2', report_id: 'r1', student_id: 'u3', student_name: 'Akosua Frimpong', created_at: '2026-09-01T12:30:00Z' },
  { id: 'c3', report_id: 'r2', student_id: 'u1', student_name: 'Ama Mensah', created_at: '2026-08-28T16:00:00Z' },
  { id: 'c4', report_id: 'r2', student_id: 'u3', student_name: 'Akosua Frimpong', created_at: '2026-08-29T09:00:00Z' },
  { id: 'c5', report_id: 'r2', student_id: 'u4', student_name: 'Yaw Boateng', created_at: '2026-08-29T14:00:00Z' },
  { id: 'c6', report_id: 'r3', student_id: 'u1', student_name: 'Ama Mensah', created_at: '2026-08-20T11:00:00Z' },
  { id: 'c7', report_id: 'r3', student_id: 'u2', student_name: 'Kwabena Owusu', created_at: '2026-08-20T13:00:00Z' },
  { id: 'c8', report_id: 'r3', student_id: 'u4', student_name: 'Yaw Boateng', created_at: '2026-08-21T08:00:00Z' },
  { id: 'c9', report_id: 'r4', student_id: 'u2', student_name: 'Kwabena Owusu', created_at: '2026-09-03T13:00:00Z' },
  { id: 'c10', report_id: 'r5', student_id: 'u3', student_name: 'Akosua Frimpong', created_at: '2026-08-30T19:00:00Z' },
  { id: 'c11', report_id: 'r5', student_id: 'u4', student_name: 'Yaw Boateng', created_at: '2026-08-31T10:00:00Z' },
  { id: 'c12', report_id: 'r7', student_id: 'u1', student_name: 'Ama Mensah', created_at: '2026-09-04T08:00:00Z' },
  { id: 'c13', report_id: 'r8', student_id: 'u1', student_name: 'Ama Mensah', created_at: '2026-08-27T11:30:00Z' },
  { id: 'c14', report_id: 'r8', student_id: 'u2', student_name: 'Kwabena Owusu', created_at: '2026-08-28T09:00:00Z' },
  { id: 'c15', report_id: 'r9', student_id: 'u2', student_name: 'Kwabena Owusu', created_at: '2026-08-18T17:00:00Z' },
];

export const mockStatusEvents: StatusEvent[] = [
  { id: 'se1', report_id: 'r1', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Ama Mensah', actor_id: 'u1', created_at: '2026-09-01T08:30:00Z' },
  { id: 'se2', report_id: 'r2', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Kwabena Owusu', actor_id: 'u2', created_at: '2026-08-28T14:15:00Z' },
  { id: 'se3', report_id: 'r2', status: 'in_progress', note: 'Maintenance team dispatched to inspect the crack', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-30T09:00:00Z' },
  { id: 'se4', report_id: 'r3', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Akosua Frimpong', actor_id: 'u3', created_at: '2026-08-20T09:00:00Z' },
  { id: 'se5', report_id: 'r3', status: 'in_progress', note: 'Supplies ordered, pending delivery', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-21T10:00:00Z' },
  { id: 'se6', report_id: 'r3', status: 'resolved', note: 'Restroom restocked and hand dryer repaired', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-24T14:00:00Z' },
  { id: 'se7', report_id: 'r4', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Yaw Boateng', actor_id: 'u4', created_at: '2026-09-03T11:45:00Z' },
  { id: 'se8', report_id: 'r5', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Ama Mensah', actor_id: 'u1', created_at: '2026-08-30T17:20:00Z' },
  { id: 'se9', report_id: 'r5', status: 'in_progress', note: 'Electrician scheduled to inspect wiring', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-09-02T08:00:00Z' },
  { id: 'se10', report_id: 'r6', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Kwabena Owusu', actor_id: 'u2', created_at: '2026-09-05T12:00:00Z' },
  { id: 'se11', report_id: 'r7', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Akosua Frimpong', actor_id: 'u3', created_at: '2026-09-04T06:30:00Z' },
  { id: 'se12', report_id: 'r8', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Yaw Boateng', actor_id: 'u4', created_at: '2026-08-27T10:00:00Z' },
  { id: 'se13', report_id: 'r8', status: 'in_progress', note: 'Facility team notified, area cordoned off', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-29T11:00:00Z' },
  { id: 'se14', report_id: 'r9', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Ama Mensah', actor_id: 'u1', created_at: '2026-08-18T15:30:00Z' },
  { id: 'se15', report_id: 'r9', status: 'in_progress', note: 'Carpenter assigned to fix door handle', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-19T09:00:00Z' },
  { id: 'se16', report_id: 'r9', status: 'resolved', note: 'Door handle replaced and lock mechanism serviced', actor_role: 'staff', actor_name: 'Daniel Tetteh', actor_id: 'u6', created_at: '2026-08-22T13:00:00Z' },
  { id: 'se17', report_id: 'r10', status: 'open', note: 'Report submitted', actor_role: 'student', actor_name: 'Akosua Frimpong', actor_id: 'u3', created_at: '2026-09-06T07:45:00Z' },
];

export const mockComments: Comment[] = [
  { id: 'cm1', report_id: 'r1', author_id: 'u2', author_name: 'Kwabena Owusu', author_role: 'student', text: 'I can confirm this. I use that bathroom every morning and the floor is always wet. Almost slipped yesterday.', created_at: '2026-09-01T10:05:00Z' },
  { id: 'cm2', report_id: 'r1', author_id: 'u3', author_name: 'Akosua Frimpong', author_role: 'student', text: 'Same here. The water has started to smell stagnant too. Needs urgent attention.', created_at: '2026-09-01T12:35:00Z' },
  { id: 'cm3', report_id: 'r2', author_id: 'u1', author_name: 'Ama Mensah', author_role: 'student', text: 'I noticed the crack last week and it was smaller. It is definitely getting wider.', created_at: '2026-08-28T16:05:00Z' },
  { id: 'cm4', report_id: 'r2', author_id: 'u6', author_name: 'Daniel Tetteh', author_role: 'staff', text: 'We have dispatched a structural assessment team. Please avoid the immediate area until further notice.', created_at: '2026-08-30T09:15:00Z' },
  { id: 'cm5', report_id: 'r3', author_id: 'u4', author_name: 'Yaw Boateng', author_role: 'student', text: 'Glad this was fixed. The restroom is fully stocked now and the dryer works.', created_at: '2026-08-25T08:00:00Z' },
  { id: 'cm6', report_id: 'r5', author_id: 'u3', author_name: 'Akosua Frimpong', author_role: 'student', text: 'The flickering happens every evening around 6pm. It seems like a wiring issue, not just a bulb.', created_at: '2026-08-30T19:05:00Z' },
  { id: 'cm7', report_id: 'r8', author_id: 'u2', author_name: 'Kwabena Owusu', author_role: 'student', text: 'I sit near that window and moved away two days ago. The panel is visibly lower than before.', created_at: '2026-08-28T09:05:00Z' },
];

export const mockVerificationSignals: VerificationSignal[] = [
  { id: 'vs1', report_id: 'r1', label: '+2 corroborated by 2 people', points: 2 },
  { id: 'vs2', report_id: 'r1', label: '+1 photo attached', points: 1 },
  { id: 'vs3', report_id: 'r1', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs4', report_id: 'r2', label: '+3 corroborated by 3 people', points: 3 },
  { id: 'vs5', report_id: 'r2', label: '+1 photo attached', points: 1 },
  { id: 'vs6', report_id: 'r2', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs7', report_id: 'r2', label: '+3 rep-confirmed', points: 3 },
  { id: 'vs8', report_id: 'r2', label: '+1 staff acknowledged', points: 1 },
  { id: 'vs9', report_id: 'r3', label: '+3 corroborated by 3 people', points: 3 },
  { id: 'vs10', report_id: 'r3', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs11', report_id: 'r3', label: '+3 rep-confirmed', points: 3 },
  { id: 'vs12', report_id: 'r3', label: '+5 resolved within 5 days', points: 5 },
  { id: 'vs13', report_id: 'r4', label: '+1 corroborated by 1 person', points: 1 },
  { id: 'vs14', report_id: 'r4', label: '+1 photo attached', points: 1 },
  { id: 'vs15', report_id: 'r4', label: '+3 detailed description (over 100 characters)', points: 3 },
  { id: 'vs16', report_id: 'r5', label: '+2 corroborated by 2 people', points: 2 },
  { id: 'vs17', report_id: 'r5', label: '+1 photo attached', points: 1 },
  { id: 'vs18', report_id: 'r5', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs19', report_id: 'r5', label: '+2 rep-confirmed', points: 2 },
  { id: 'vs20', report_id: 'r6', label: '+1 detailed description (over 100 characters)', points: 1 },
  { id: 'vs21', report_id: 'r6', label: '+2 rep-confirmed', points: 2 },
  { id: 'vs22', report_id: 'r7', label: '+1 corroborated by 1 person', points: 1 },
  { id: 'vs23', report_id: 'r7', label: '+1 photo attached', points: 1 },
  { id: 'vs24', report_id: 'r7', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs25', report_id: 'r8', label: '+2 corroborated by 2 people', points: 2 },
  { id: 'vs26', report_id: 'r8', label: '+1 photo attached', points: 1 },
  { id: 'vs27', report_id: 'r8', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs28', report_id: 'r8', label: '+3 rep-confirmed', points: 3 },
  { id: 'vs29', report_id: 'r9', label: '+1 corroborated by 1 person', points: 1 },
  { id: 'vs30', report_id: 'r9', label: '+4 detailed description (over 100 characters)', points: 4 },
  { id: 'vs31', report_id: 'r9', label: '+3 rep-confirmed', points: 3 },
  { id: 'vs32', report_id: 'r10', label: '+1 photo attached', points: 1 },
  { id: 'vs33', report_id: 'r10', label: '+3 detailed description (over 100 characters)', points: 3 },
];

export const mockNotifications: Notification[] = [
  { id: 'n1', type: 'corroboration', report_id: 'r1', report_description: 'Pentagon Hall, Common Bathroom: leaking shower', message: 'Kwabena Owusu corroborated your report about the leaking shower', created_at: '2026-09-01T10:00:00Z', read: false },
  { id: 'n2', type: 'corroboration', report_id: 'r1', report_description: 'Pentagon Hall, Common Bathroom: leaking shower', message: 'Akosua Frimpong also confirmed the leaking shower issue', created_at: '2026-09-01T12:30:00Z', read: false },
  { id: 'n3', type: 'status_change', report_id: 'r5', report_description: 'Independence Hall, Kitchen Area: flickering light', message: 'Your report status changed to In Progress: an electrician has been scheduled', created_at: '2026-09-02T08:00:00Z', read: false },
  { id: 'n4', type: 'comment', report_id: 'r1', report_description: 'Pentagon Hall, Common Bathroom: leaking shower', message: 'Kwabena Owusu commented on your report', created_at: '2026-09-01T10:05:00Z', read: true },
  { id: 'n5', type: 'rep_action', report_id: 'r2', report_description: 'Republic Hall, Block A Stairwell: wall crack', message: 'Rep Esi Ansah confirmed your report about the stairwell crack', created_at: '2026-08-29T15:00:00Z', read: true },
  { id: 'n6', type: 'status_change', report_id: 'r9', report_description: 'Pentagon Hall, Room 204: loose door handle', message: 'Your report has been marked as Resolved: door handle replaced', created_at: '2026-08-22T13:00:00Z', read: true },
];

export const mockInternalNotes: InternalNote[] = [
  {
    id: 'in1',
    report_id: 'r2',
    author_id: 'u6',
    author_name: 'Daniel Tetteh',
    author_role: 'staff',
    text: 'Structural engineer team contacted. On-site acoustic inspection scheduled for Thursday morning.',
    created_at: '2026-08-30T10:15:00Z',
  },
  {
    id: 'in2',
    report_id: 'r5',
    author_id: 'u6',
    author_name: 'Daniel Tetteh',
    author_role: 'staff',
    text: 'Replacement ballast and LED tube ordered from central warehouse. ETA 24 hours.',
    created_at: '2026-09-02T09:30:00Z',
  },
];

